version: '3'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile.spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node-app
    ports:
      - "3000:3000"

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
